import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, MapPin, Calendar, Award, Tag } from 'lucide-react';

interface Report {
  id: string;
  title: string;
  abstract: string;
  summary: string;
  outcomes: string[];
  thumbnail_url: string;
  file_url: string;
  accredited: boolean;
  area: string;
  tags: string[];
  country: string;
  publish_year: number;
}

// Mock data — reemplazar con fetch a API/DB cuando esté listo
const MOCK_REPORTS: Record<string, Report> = {
  '1': {
    id: '1',
    title: 'Global Economic Outlook 2025: Trends and Forecasts',
    abstract:
      'This comprehensive report examines the current state of the global economy and provides detailed forecasts for the coming year. Key areas of focus include inflation trends, employment rates, and GDP growth across major economies. The analysis incorporates data from over 50 countries and uses advanced econometric modeling to generate reliable forecasts. Special attention is given to emerging markets and their integration into the global financial system.',
    summary:
      'Through engagement with leading economic research institutions, this organization learned that Social Return on Investment (SROI) quantifies social benefits and therefore adopted this approach to assess the social impact of economic development programs. SROI enables them to present, with concrete data, how social inputs translate into outcomes so external audiences can clearly understand contributions to long-term economic development. It also serves as a basis to review and optimize current services and to replicate the model, thereby expanding and deepening social value.\n\nThis project is an evaluation-type SROI; covering 1 January 2024 to 31 December 2024 (one year). The program generated an SROI of 4.57; sensitivity analysis ranged 3.46–5.08, indicating stable and high social value creation. From stakeholder consultations and feedback, the key outcomes are as follows:',
    outcomes: [
      'Communities: positive economic changes, including improved financial stability, reduced poverty indicators, and increased long-term economic resilience across regions',
      'Businesses: reduced operational uncertainty and improved strategic planning capabilities due to access to reliable economic forecasting tools',
      'Policy makers: enhanced evidence-based decision-making skills, gained new analytical frameworks, and heightened awareness of cross-sector economic interdependencies',
      'Research Organizations: expanded international collaborations, strengthened analytical capabilities, and innovation in economic modeling—demonstrating overall contribution to sustainable development',
    ],
    thumbnail_url: 'https://images.unsplash.com/photo-1579532537598-459e26a7fa38?w=400&h=520&fit=crop',
    file_url: '#',
    accredited: true,
    area: 'Economics',
    tags: ['economy', 'forecast', 'GDP', 'inflation', 'global'],
    country: 'Global',
    publish_year: 2025,
  },
  '2': {
    id: '2',
    title: 'Climate Change Impact Assessment: Agriculture Sector',
    abstract:
      'An in-depth analysis of how climate change is affecting agricultural production worldwide. This report covers crop yield variations, water scarcity challenges, and adaptation strategies being implemented by farmers and governments. Special attention is given to vulnerable regions in sub-Saharan Africa and South Asia, where food security is most at risk.',
    summary:
      'The agricultural sector faces unprecedented challenges as climate change intensifies, disrupting traditional growing seasons and reducing yields across staple crops globally. This SROI evaluation examines the social and economic returns generated by climate adaptation programs implemented in 2024, measuring outcomes across multiple stakeholder groups.\n\nThis project is an evaluation-type SROI; covering 1 January 2024 to 31 December 2024. The program generated an SROI of 3.82; sensitivity analysis ranged 2.95–4.71, indicating consistent social value creation. From stakeholder consultations and feedback, the key outcomes are as follows:',
    outcomes: [
      'Farmers: improved crop resilience, reduced losses from extreme weather events, and increased adoption of sustainable agricultural practices',
      'Rural communities: enhanced food security, stabilized local economies, and improved access to agricultural support networks',
      'Governments: better policy frameworks for climate adaptation, strengthened inter-agency coordination, and improved resource allocation efficiency',
      'Environmental organizations: expanded monitoring capabilities, deeper partnerships with farming communities, and innovation in sustainable land management approaches',
    ],
    thumbnail_url: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=400&h=520&fit=crop',
    file_url: '#',
    accredited: false,
    area: 'Agriculture',
    tags: ['climate', 'agriculture', 'food security', 'adaptation'],
    country: 'Global',
    publish_year: 2025,
  },
  '3': {
    id: '3',
    title: 'Digital Transformation in Healthcare: A Global Perspective',
    abstract:
      'Exploring the rapid digitalization of healthcare services across developed and developing nations. Topics include telemedicine adoption rates, electronic health records implementation, AI-assisted diagnostics, and the regulatory frameworks governing digital health innovations. The report provides actionable recommendations for healthcare systems at all stages of digital maturity.',
    summary:
      'The digital transformation of healthcare represents one of the most significant shifts in medical service delivery in modern history. This SROI evaluation assesses the social return generated by digital health initiatives implemented across multiple healthcare systems in 2024, focusing on patient outcomes, provider efficiency, and systemic changes.\n\nThis project is an evaluation-type SROI; covering 1 January 2024 to 31 December 2024. The digital health initiative generated an SROI of 5.21; sensitivity analysis ranged 4.10–6.33, indicating exceptional social value creation. From stakeholder consultations and feedback, the key outcomes are as follows:',
    outcomes: [
      'Patients: improved access to specialized care, reduced travel burdens, faster diagnosis times, and enhanced management of chronic conditions through digital monitoring',
      'Healthcare providers: increased operational efficiency, reduced administrative workload, improved diagnostic accuracy through AI tools, and expanded capacity to serve remote populations',
      'Health systems: lower overall costs through prevention and early intervention, better resource allocation, and stronger data infrastructure for public health decision-making',
      'Technology partners: validated real-world application of digital health solutions, refined products based on clinical feedback, and established models for sustainable healthcare technology deployment',
    ],
    thumbnail_url: 'https://images.unsplash.com/photo-1576091160550-112173f7f869?w=400&h=520&fit=crop',
    file_url: '#',
    accredited: true,
    area: 'Healthcare',
    tags: ['digital health', 'telemedicine', 'AI', 'healthcare systems'],
    country: 'USA',
    publish_year: 2025,
  },
  '4': {
    id: '4',
    title: 'Renewable Energy Transition: Policy and Implementation',
    abstract:
      'A comprehensive study of renewable energy policies and their real-world implementation across different regions. The report analyzes solar, wind, and hydroelectric projects, their efficiency rates, cost analysis, and environmental benefits. It also examines government incentives and international agreements that are accelerating the clean energy transition.',
    summary:
      'The global transition to renewable energy represents the most consequential infrastructure shift of the 21st century. This SROI evaluation measures the social and economic returns from renewable energy transition programs implemented across multiple European countries in 2024, capturing outcomes for communities, industries, and the environment.\n\nThis project is an evaluation-type SROI; covering 1 January 2024 to 31 December 2024. The renewable energy transition program generated an SROI of 6.14; sensitivity analysis ranged 4.88–7.40, indicating very high social value creation. From stakeholder consultations and feedback, the key outcomes are as follows:',
    outcomes: [
      'Local communities: reduced energy costs, improved air quality, creation of skilled green jobs, and increased energy independence from volatile fossil fuel markets',
      'Industry and businesses: long-term cost predictability, compliance with sustainability requirements, enhanced corporate reputation, and new market opportunities in the green economy',
      'Government bodies: progress toward climate commitments, strengthened energy security, modernized grid infrastructure, and improved public health outcomes from reduced pollution',
      'Environmental stakeholders: measurable reductions in carbon emissions, preserved ecosystems through responsible siting of renewable installations, and accelerated transition away from extractive industries',
    ],
    thumbnail_url: 'https://images.unsplash.com/photo-1509391366360-2e938f0deba0?w=400&h=520&fit=crop',
    file_url: '#',
    accredited: true,
    area: 'Energy',
    tags: ['renewable energy', 'solar', 'wind', 'climate policy', 'Europe'],
    country: 'Europe',
    publish_year: 2025,
  },
};

function GeometricDecoration() {
  return (
    <svg
      className="absolute top-0 right-0 h-full w-48 sm:w-64"
      viewBox="0 0 260 200"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      preserveAspectRatio="xMaxYMid meet"
    >
      {/* Back triangles */}
      <polygon points="160,0 260,0 260,140" fill="rgba(255,255,255,0.08)" />
      <polygon points="200,0 260,0 260,80" fill="rgba(255,255,255,0.12)" />
      {/* Teal-light triangle */}
      <polygon points="180,10 260,10 260,110" fill="rgba(255,255,255,0.15)" />
      {/* Pink/mauve accent */}
      <polygon points="220,0 260,0 260,60" fill="rgba(200,170,190,0.35)" />
      {/* Pale blue */}
      <polygon points="140,0 220,0 220,90" fill="rgba(180,230,235,0.25)" />
      {/* Front overlap */}
      <polygon points="200,0 260,0 260,90" fill="rgba(255,255,255,0.1)" />
    </svg>
  );
}

export default async function ReportDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const report = MOCK_REPORTS[id];

  if (!report) {
    notFound();
  }

  const summaryParagraphs = report.summary.split('\n\n').filter(Boolean);

  return (
    <div className="h-full overflow-y-auto bg-white">
      {/* Header */}
      <header className="relative bg-[#0bb4be] overflow-hidden">
        <GeometricDecoration />
        <div className="relative z-10 max-w-4xl mx-auto px-6 py-10 sm:py-14 text-center">
          <p className="text-white/70 text-sm font-medium mb-2 uppercase tracking-wider">
            Base de Datos de Reportes
          </p>
          <h1 className="text-white text-2xl sm:text-3xl lg:text-4xl font-bold leading-tight">
            {report.title}
          </h1>
        </div>
      </header>

      {/* Back link */}
      <div className="max-w-4xl mx-auto px-6 pt-6">
        <Link
          href="/reports"
          className="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-slate-800 transition-colors"
        >
          <ArrowLeft size={15} />
          Volver al listado
        </Link>
      </div>

      {/* Metadata chips */}
      <div className="max-w-4xl mx-auto px-6 pt-4 flex flex-wrap gap-2">
        <span className="inline-flex items-center gap-1.5 text-xs font-medium bg-slate-100 text-slate-600 px-3 py-1.5 rounded-full">
          <MapPin size={12} />
          {report.country}
        </span>
        <span className="inline-flex items-center gap-1.5 text-xs font-medium bg-slate-100 text-slate-600 px-3 py-1.5 rounded-full">
          <Calendar size={12} />
          {report.publish_year}
        </span>
        <span className="inline-flex items-center gap-1.5 text-xs font-medium bg-slate-100 text-slate-600 px-3 py-1.5 rounded-full">
          <Tag size={12} />
          {report.area}
        </span>
        {report.accredited && (
          <span className="inline-flex items-center gap-1.5 text-xs font-medium bg-emerald-50 text-emerald-700 px-3 py-1.5 rounded-full border border-emerald-200">
            <Award size={12} />
            Acreditado
          </span>
        )}
      </div>

      {/* Main content */}
      <article className="max-w-4xl mx-auto px-6 py-8 space-y-8">
        {/* Abstract + cover image */}
        <section className="grid grid-cols-1 md:grid-cols-[1fr_auto] gap-8 items-start">
          <div>
            <h2 className="text-base font-bold text-slate-900 mb-3">Abstract</h2>
            <p className="text-sm text-slate-700 leading-relaxed">{report.abstract}</p>
          </div>
          {report.thumbnail_url && (
            <div className="w-full md:w-44 flex-shrink-0">
              <img
                src={report.thumbnail_url}
                alt={`Portada: ${report.title}`}
                className="w-full md:w-44 rounded-lg shadow-md object-cover aspect-[4/5]"
              />
            </div>
          )}
        </section>

        {/* Summary */}
        <section className="space-y-4">
          {summaryParagraphs.map((paragraph, i) => (
            <p key={i} className="text-sm text-slate-700 leading-relaxed">
              {paragraph}
            </p>
          ))}
        </section>

        {/* Outcomes / bullet points */}
        {report.outcomes.length > 0 && (
          <section>
            <ul className="space-y-4">
              {report.outcomes.map((outcome, i) => (
                <li key={i} className="flex gap-3 items-start">
                  <span className="mt-0.5 text-[#0bb4be] text-xs leading-none flex-shrink-0 pt-1">
                    ▼
                  </span>
                  <p className="text-sm text-slate-700 leading-relaxed">{outcome}</p>
                </li>
              ))}
            </ul>
          </section>
        )}

        {/* Tags */}
        {report.tags.length > 0 && (
          <section className="pt-2">
            <div className="flex flex-wrap gap-2">
              {report.tags.map((tag) => (
                <span
                  key={tag}
                  className="text-xs bg-[#0bb4be]/10 text-[#0bb4be] px-3 py-1 rounded-full font-medium"
                >
                  {tag}
                </span>
              ))}
            </div>
          </section>
        )}

        {/* Download button */}
        <section className="flex justify-center pt-4 pb-8">
          <a
            href={report.file_url}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 bg-[#0bb4be] hover:bg-[#09a0a9] text-white font-semibold px-8 py-3 rounded-md transition-colors text-sm"
          >
            Descargar el PDF
          </a>
        </section>
      </article>
    </div>
  );
}
